/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(multiply_const.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3ecd42c4c9bf614d4a821013da4f15bd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <cudademo/multiply_const.h>
// pydoc.h is automatically generated in the build directory
#include <multiply_const_pydoc.h>

void bind_multiply_const(py::module& m)
{

    using multiply_const    = gr::cudademo::multiply_const;


    py::class_<multiply_const, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<multiply_const>>(m, "multiply_const", D(multiply_const))

        .def(py::init(&multiply_const::make),
           py::arg("k"),
           D(multiply_const,make)
        )
        
        .def("set_k", &multiply_const::set_k);


        ;




}








